"""Demo GSTR-2B payloads in GSTN/GSP envelope shape.

Two fetches of the same tax period, days apart:

* `inconsistent` — the first fetch. 14 suppliers have not filed, so their invoices are
  absent from the 2B entirely; 7 invoice numbers are mis-keyed, 5 carry a wrong tax
  amount, 4 are filed but ITC-blocked.
* `corrected` — the second fetch, after chasing. **Nine of those 14 have since filed**,
  so this payload carries *more* invoices than the first (75 vs 66). The other five are
  chronic non-filers and are still absent. Clerical, amount and ITC defects are
  unchanged between the two: a typo does not fix itself by waiting, and an ITC block is
  a portal ruling.

That 9-invoice difference is the entire point of having two variants — it is what the
period view narrates as "9 filed since the last check", and it only reads as real if
the second payload genuinely contains more than the first.

Both payloads are generated by `scripts/generate_demo_dataset.py` together with the
purchase register they reconcile against, and both go through
`parse_gsp_gstr2b_response` unchanged.

Why the files are generated rather than hand-mutated: this module used to hold the
defect set as literal invoice numbers and derive the counts from `len()` of those
dicts. That is a claim, not a measurement, and it was wrong — a clerical rewrite used a
`2 -> Z` swap, which `clerical_key` does not fold, so the row silently became a missing
invoice on both sides while the counters kept reporting a clerical. The generator now
measures the counts by running the real matcher over the shipped pair.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Literal

from lockstep.core.exceptions import ValidationError

Gstr2bVariant = Literal["inconsistent", "corrected"]

_FIXTURES = Path(__file__).resolve().parents[3] / "tests" / "fixtures"

#: One file per variant. `corrected` is the larger of the two.
_PAYLOAD_PATHS: dict[str, Path] = {
    "inconsistent": _FIXTURES / "gsp_gstr2b_sample.json",
    "corrected": _FIXTURES / "gsp_gstr2b_corrected.json",
}

#: What each variant reconciles to against the shipped register — measured by
#: `scripts/generate_demo_dataset.py`, which runs `match_invoices` over the real files
#: rather than counting constants. Keys match the FE's `Gstr2bDefects` shape.
_DEFECTS: dict[str, dict[str, int]] = {
    "inconsistent": {
        "exact": 50,
        "clerical": 7,
        "amount_mismatch": 5,
        "missing_in_2b": 14,
        "itc_ineligible": 4,
    },
    "corrected": {
        "exact": 59,
        "clerical": 7,
        "amount_mismatch": 5,
        "missing_in_2b": 5,
        "itc_ineligible": 4,
    },
}


def parse_variant(raw: str | None) -> Gstr2bVariant:
    variant = (raw or "corrected").strip().lower()
    if variant not in _PAYLOAD_PATHS:
        raise ValidationError('variant must be "inconsistent" or "corrected"')
    return variant  # type: ignore[return-value]


@lru_cache(maxsize=2)
def _load(variant: str) -> dict:
    path = _PAYLOAD_PATHS[variant]
    if not path.exists():
        raise ValidationError(
            f"Demo GSTR-2B payload missing: {path.name}. "
            f"Run `uv run python scripts/generate_demo_dataset.py` to regenerate it."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def _b2b_vendors(payload: dict) -> list[dict]:
    return payload["data"]["data"]["data"]["docdata"]["b2b"]


def _invoice_count(payload: dict) -> int:
    return sum(len(vendor.get("inv", [])) for vendor in _b2b_vendors(payload))


def defects_for(variant: Gstr2bVariant) -> dict[str, int]:
    return dict(_DEFECTS[variant])


def get_gstr2b_payload(variant: Gstr2bVariant = "corrected") -> dict:
    """The raw GSTN envelope. Returned as a deep-ish copy via json round-trip so a
    caller mutating it cannot poison the cache."""
    return json.loads(json.dumps(_load(variant)))


def get_gstr2b_mock(variant: Gstr2bVariant = "corrected") -> dict:
    payload = get_gstr2b_payload(variant)
    return {
        "variant": variant,
        "count": _invoice_count(payload),
        "defects": defects_for(variant),
        "data": payload,
    }
